### ISSUE TITLE
Havoc Brother Disciples Can't add Frenzy

### ISSUE THREAD

**Issue by Syskoras** [OnePageRules/GrimdarkFuture#19]
Can't Upgrade Units with Frenzy

**Comment by Darguth** [comment]
@Syskoras you'll have to be more specific. I just checked Talon Raptors and it worked fine. Select Disciples of War from the disciple selector in the main list and then the Disciples of War upgrade on the individual unit.

**Comment by Syskoras** [comment]
I'm sorry there was a misunderstanding on the rules on my side. Everything works correctly. I tried to upgrade Berserkers with this, which is against the rules.
